spring:
  application:
    name: edupulse_backend

  datasource:
    url: jdbc:postgresql://localhost:5432/edupulse_db
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: test-secret-value-for-debugging-only
  expiration: 86400000